### ISSUE TITLE
make adding message in code block optional

### ISSUE THREAD

**Issue by hovosanoyan** [renderforest/notification-hooks#20]
Slack module is always [wrapping](https://github.com/renderforest/notification-hooks/blob/master/src/lib/slack.js#L25) text into code block (described in [slack docs](https://api.slack.com/docs/messages)). 
In this blocks some characters are replaced with character code (after `JSON.stringify`).
Also this behavior is not always best so better to make it optional.

**Comment by AlbertHambardzumyan** [comment]
#22
